service: aws-python-http-api-project2
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  informacion:
    handler: handler.informacion
    events:
      - httpApi:
          path: /info
          method: get
